name: Package and release

on:
  push:
    tags:
      - '**'   # run when you push an annotated tag

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # allow publishing GitHub releases

    env:
      CF_API_KEY: ${{ secrets.CF_API_KEY }}
      # WOWI_API_TOKEN: ${{ secrets.WOWI_API_TOKEN }}
      # WAGO_API_TOKEN: ${{ secrets.WAGO_API_TOKEN }}
      GITHUB_OAUTH: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # needed for changelog generation

      - name: Package and release
        uses: BigWigsMods/packager@v2
        # with:
        #   args: -g classic     # example: force Classic only
        #   # or don't upload to WoWInterface:
        #   # args: -w 0
